
package pe.com.comercio.eai.services.gestionsuscripcionws.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import pe.com.comercio.eai.services.gestionsuscripcionws.ws.types.ActualizarSuscripcionRequest;
import pe.com.comercio.eai.services.gestionsuscripcionws.ws.types.ActualizarSuscripcionResponse;
import pe.com.comercio.eai.services.gestionsuscripcionws.ws.types.EliminarSuscripcionRequest;
import pe.com.comercio.eai.services.gestionsuscripcionws.ws.types.EliminarSuscripcionResponse;
import pe.com.comercio.eai.services.gestionsuscripcionws.ws.types.ListarSuscripcionRequest;
import pe.com.comercio.eai.services.gestionsuscripcionws.ws.types.ListarSuscripcionResponse;
import pe.com.comercio.eai.services.gestionsuscripcionws.ws.types.ObjectFactory;
import pe.com.comercio.eai.services.gestionsuscripcionws.ws.types.RegistrarSuscripcionRequest;
import pe.com.comercio.eai.services.gestionsuscripcionws.ws.types.RegistrarSuscripcionResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GestionSuscripcionWSPortType", targetNamespace = "http://comercio.com.pe/eai/services/GestionSuscripcionWS/ws")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GestionSuscripcionWSPortType {


    /**
     * 
     * @param request
     * @return
     *     returns pe.com.comercio.eai.services.gestionsuscripcionws.ws.types.RegistrarSuscripcionResponse
     */
    @WebMethod(action = "http://comercio.com.pe/eai/services/GestionSuscripcionWS/ws/registrarSuscripcion")
    @WebResult(name = "registrarSuscripcionResponse", targetNamespace = "http://comercio.com.pe/eai/services/GestionSuscripcionWS/ws/types", partName = "response")
    public RegistrarSuscripcionResponse registrarSuscripcion(
        @WebParam(name = "registrarSuscripcionRequest", targetNamespace = "http://comercio.com.pe/eai/services/GestionSuscripcionWS/ws/types", partName = "request")
        RegistrarSuscripcionRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns pe.com.comercio.eai.services.gestionsuscripcionws.ws.types.ListarSuscripcionResponse
     */
    @WebMethod(action = "http://comercio.com.pe/eai/services/GestionSuscripcionWS/ws/listarSuscripcion")
    @WebResult(name = "listarSuscripcionResponse", targetNamespace = "http://comercio.com.pe/eai/services/GestionSuscripcionWS/ws/types", partName = "response")
    public ListarSuscripcionResponse listarSuscripcion(
        @WebParam(name = "listarSuscripcionRequest", targetNamespace = "http://comercio.com.pe/eai/services/GestionSuscripcionWS/ws/types", partName = "request")
        ListarSuscripcionRequest request);
    
    /**
     * 
     * @param request
     * @return
     *     returns pe.com.comercio.eai.services.gestionsuscripcionws.ws.types.EliminarSuscripcionResponse
     */
    @WebMethod(action = "http://comercio.com.pe/eai/services/GestionSuscripcionWS/ws/eliminarSuscripcion")
    @WebResult(name = "eliminarSuscripcionResponse", targetNamespace = "http://comercio.com.pe/eai/services/GestionSuscripcionWS/ws/types", partName = "response")
    public EliminarSuscripcionResponse eliminarSuscripcion(
        @WebParam(name = "eliminarSuscripcionRequest", targetNamespace = "http://comercio.com.pe/eai/services/GestionSuscripcionWS/ws/types", partName = "request")
        EliminarSuscripcionRequest request);
    
    /**
     * 
     * @param request
     * @return
     *     returns pe.com.comercio.eai.services.gestionsuscripcionws.ws.types.ActualizarSuscripcionResponse
     */
    @WebMethod(action = "http://comercio.com.pe/eai/services/GestionSuscripcionWS/ws/actualizarSuscripcion")
    @WebResult(name = "actualizarSuscripcionResponse", targetNamespace = "http://comercio.com.pe/eai/services/GestionSuscripcionWS/ws/types", partName = "response")
    public ActualizarSuscripcionResponse actualizarSuscripcion(
        @WebParam(name = "actualizarSuscripcionRequest", targetNamespace = "http://comercio.com.pe/eai/services/GestionSuscripcionWS/ws/types", partName = "request")
        ActualizarSuscripcionRequest request);

}
