
package pe.com.comercio.eai.services.gestionsuscripcionws.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GestionSuscripcionWSService", targetNamespace = "http://comercio.com.pe/eai/services/GestionSuscripcionWS/ws", wsdlLocation = "file:/D:/GUARDAR%20ARCHIVOS%20AQUI/Prof%20Richard/Sesion%208/P1/GestionSuscripcionWS.wsdl")
public class GestionSuscripcionWSService
    extends Service
{

    private final static URL GESTIONSUSCRIPCIONWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException GESTIONSUSCRIPCIONWSSERVICE_EXCEPTION;
    private final static QName GESTIONSUSCRIPCIONWSSERVICE_QNAME = new QName("http://comercio.com.pe/eai/services/GestionSuscripcionWS/ws", "GestionSuscripcionWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/GUARDAR%20ARCHIVOS%20AQUI/Prof%20Richard/Sesion%208/P1/GestionSuscripcionWS.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GESTIONSUSCRIPCIONWSSERVICE_WSDL_LOCATION = url;
        GESTIONSUSCRIPCIONWSSERVICE_EXCEPTION = e;
    }

    public GestionSuscripcionWSService() {
        super(__getWsdlLocation(), GESTIONSUSCRIPCIONWSSERVICE_QNAME);
    }

    public GestionSuscripcionWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GESTIONSUSCRIPCIONWSSERVICE_QNAME, features);
    }

    public GestionSuscripcionWSService(URL wsdlLocation) {
        super(wsdlLocation, GESTIONSUSCRIPCIONWSSERVICE_QNAME);
    }

    public GestionSuscripcionWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GESTIONSUSCRIPCIONWSSERVICE_QNAME, features);
    }

    public GestionSuscripcionWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GestionSuscripcionWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GestionSuscripcionWSPortType
     */
    @WebEndpoint(name = "GestionSuscripcionWSSOAP11Port")
    public GestionSuscripcionWSPortType getGestionSuscripcionWSSOAP11Port() {
        return super.getPort(new QName("http://comercio.com.pe/eai/services/GestionSuscripcionWS/ws", "GestionSuscripcionWSSOAP11Port"), GestionSuscripcionWSPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GestionSuscripcionWSPortType
     */
    @WebEndpoint(name = "GestionSuscripcionWSSOAP11Port")
    public GestionSuscripcionWSPortType getGestionSuscripcionWSSOAP11Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://comercio.com.pe/eai/services/GestionSuscripcionWS/ws", "GestionSuscripcionWSSOAP11Port"), GestionSuscripcionWSPortType.class, features);
    }

    /**
     * 
     * @return
     *     returns GestionSuscripcionWSPortType
     */
    @WebEndpoint(name = "GestionSuscripcionWSSOAP12Port")
    public GestionSuscripcionWSPortType getGestionSuscripcionWSSOAP12Port() {
        return super.getPort(new QName("http://comercio.com.pe/eai/services/GestionSuscripcionWS/ws", "GestionSuscripcionWSSOAP12Port"), GestionSuscripcionWSPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GestionSuscripcionWSPortType
     */
    @WebEndpoint(name = "GestionSuscripcionWSSOAP12Port")
    public GestionSuscripcionWSPortType getGestionSuscripcionWSSOAP12Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://comercio.com.pe/eai/services/GestionSuscripcionWS/ws", "GestionSuscripcionWSSOAP12Port"), GestionSuscripcionWSPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GESTIONSUSCRIPCIONWSSERVICE_EXCEPTION!= null) {
            throw GESTIONSUSCRIPCIONWSSERVICE_EXCEPTION;
        }
        return GESTIONSUSCRIPCIONWSSERVICE_WSDL_LOCATION;
    }

}
